In [1]:
!pip install numpy

In [ ]:
import numpy as np

## create array using numpy
## create a 1d array
arr1=np.array([1,2,3,4,5])
print(arr1)
# this is not a list
print(type(arr1))
# we can also see the shape of array
print(arr1.shape)
# in 1d array there are no rows and columns
# reshaping 1d array to 2d array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # One row and five columns
# Now it will respond as array([[1, 2, 3, 4, 5]]) which has two [[]] brackets which shows it is 2d array. similarly 3d will have three brackets

# similarly we can use two [[]] for creating 2d and [[[]]] for creating 3d array
arr3 = np.array([[1,2,3,4,5]])
print(arr3)

# for multiple rows
arr4 = np.array([[1,2,3,4], [5,6,7,8]])
print(arr4)
print(arr4.shape) # (2,4) cuz there are two rows and four columns

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
[[1 2 3 4 5]]
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [13]:
# Creating arrays with inbuilt functions
np.arange(0,10,2) # range from 0 to 10 with step 2
# We can use multiple func like this
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
# Inbuilt functions for Numpy
np.ones((3,4)) # make an array with rows,columns consisting 1 as element

np.eye(3) # Creates an identiny matrix with argument as number of diagonal elements

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Attributes of Numpy
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int64 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [18]:
## Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element Wise addition
print("Addition:", arr1+arr2)

# Elememt Wise Subtraction
print("Subtraction: ", arr2 - arr1)

# similarly is multiplication, division etc

Addition: [11 22 33 44 55]
Subtraction:  [ 9 18 27 36 45]


In [ ]:
## Universal Function
# functions that applies to entire array
arr = np.array([2,3,4,5,6])

# square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Natural log
print(np.log(arr))

# Similarly there are many more

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [29]:
## Array slicing and indexing

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Array : \n", arr)

# how do i access a single element from array
# lets pick up 1
# Know the row and column which is its index

arr[0][0]

# lets pick 7, 8, 11, 12 (using slicing)

arr[1:, 2:]

# lets pick 3, 4, 7, 8

arr[0:2, 2:4]

# So we can pick up any elements using this slicing and indexing mechanism

## Modify array elements
arr[0,0] = 100
print(arr)

arr[1:] = 99
print(arr)

arr[1:3, 2:4] = 34
print(arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [ 99  99  99  99]
 [ 99  99  99  99]]
[[100   2   3   4]
 [ 99  99  34  34]
 [ 99  99  34  34]]


In [31]:
## Statistical concepts--Normalization

arr = np.array([[1, 2, 3], [4, 5, 6]]) 

data = np.array([1, 2, 3, 4, 5]) 

# Calculate statistics
mean = np.mean(data) 
std_dev = np.std(data) 

# Normalize the data
normalized_data = (data - mean) / std_dev 

print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [32]:
# --- Statistical Operations ---
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [ ]:
# Logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

# anything local operation can be used like and, or, not

array([5, 6, 7, 8])